spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: lb://ORDER-SERVICE
              predicates:
              - Path=/api/v1/orders/**
            - id: inventory-service-route
              uri: lb://INVENTORY-SERVICE
              predicates:
              - Path=/api/v1/products/**
            - id: auth-service-route
              uri: lb://AUTH-SERVICE
              predicates:
              - Path=/api/v1/auths/**
          discovery:
            locator:
              enabled: true
jwt:
  secret: a103620fec951f287fe3147a63be54f0288553134d1b8ef51188da3ddad629d6
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
server:
  port: 8085